### PR TITLE
Fix the hyperlink on CONTRIBUTING.md, because it was screwed up somehow

### PR DESCRIPTION
**Pull request by proudmuslim-dev**

### CODE REVIEW

**Comment by proudmuslim-dev** [comment]
I hate my life

**Comment by DanterusDev** [comment]
good

**Comment by proudmuslim-dev** [comment]
Roped another fix into this PR because why not; Working on build instructions or whatever soon

**Comment by proudmuslim-dev** [comment]
UPDATE: **I wrote the build instructions, you're welcome**

**Pull request merged**
